[package]
name = "sonant"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]

[dependencies]
arrayvec = { version = "0.4", default-features = false }
byteorder = "1.2"
failure = "0.1"
failure_derive = { version = "0.1", optional = true }
rand = "0.5"

[dev-dependencies]
colored = "1.6"
cpal = "0.8"

[features]
default = ["std"]
std = ["failure_derive"]
